# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # defaults: 
    #   run:
    #     working-directory: ./faiz-ui/
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
      
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Check Out Response Code
      uses: actions/checkout@v3
    - run: echo "The ${{github.repository}} has been cloned to the runner"
    - run: echo "The workflow is now ready to test your code on the runner"
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      
    - run: npm install pnpm -g
    - run: pnpm config set registry https://registry.npmmirror.com
    - run: pnpm install
      working-directory: './03-create-game'
    - run: pnpm build
      working-directory: './03-create-game'
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "./03-create-game/dist"
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
